name: Mate
description: A Flutter-based mobile client for the "Mate" project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5

  # Replace this:
  # chess_board: ^1.0.3
  # With:
  flutter_chess_board: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
